schema_version = "1.0.0"

id = "fly_nav"
version = "0.2.0"
name = "Fly Nav"
tagline = "Seamless game engine style viewport fly navigation"
maintainer = "Albert O'Shea"
type = "add-on"

tags = ["Navigation", "3D View"]

blender_version_min = "4.0.0"

license = ["SPDX:GPL-3.0-or-later"]

website = "https://github.com/AMC-Albert/fly_nav_ext"
