schema_version = "1.0.0"

id = "hdiff_tool"
version = "0.4.1"
name = "HDiff Tool"
tagline = "Create incremental versions of blend files with a focus on extreme storage space effeciency."
maintainer = "Albert O'Shea"
type = "add-on"

tags = ["Development", "Pipeline", "Import-Export", "System"]

blender_version_min = "4.0.0"

license = ["SPDX:GPL-3.0-or-later"]

# Optional: Add website if you have one
# website = "https://github.com/yourusername/hdiff_tool_ext"

# Python Wheels (for bundling external dependencies)
# Pillow wheels for all supported platforms
wheels = [
	"./wheels/pillow-10.4.0-cp311-cp311-win_amd64.whl",
	"./wheels/pillow-10.4.0-cp311-cp311-macosx_11_0_arm64.whl",
	"./wheels/pillow-10.4.0-cp311-cp311-manylinux_2_28_x86_64.whl",
]

[permissions]
files = "Access local files for preview image management"

# Optional: build settings
[build]
paths_exclude_pattern = [
	"__pycache__/",
	"*.pyc",
	"*.ps1",
	"download_wheels.ps1",
	"extracted_wheels/",
]
